apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-usuarios-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-usuarios-app
  template:
    metadata:
      labels:
        app: ms-usuarios-app
    spec:
      containers:
        - name: ms-usuarios
          image: ${DOCKER_IMAGE}
          ports:
            - containerPort: 8092
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://ms-usuarios-db:5432/microservicio_db
            - name: SPRING_DATASOURCE_USERNAME
              value: msdb
            - name: SPRING_DATASOURCE_PASSWORD
              value: holamundo123
            - name: NOTIFICACIONES_URL
              value: http://host.docker.internal:8090/api/notificaciones/enviar
---
apiVersion: v1
kind: Service
metadata:
  name: ms-usuarios-service
spec:
  type: LoadBalancer
  selector:
    app: ms-usuarios-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8092